# Generated by Django 4.2.1 on 2023-05-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255,
                                     verbose_name="Название категории"),
                ),
                ("slug", models.SlugField(verbose_name="URL")),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
                "db_table": "ProductCategories",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255,
                                     verbose_name="Название товара"),
                ),
                (
                    "specifications",
                    models.TextField(verbose_name="Характристики товара"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="products",
                                      verbose_name="Фото товара"),
                ),
                ("price", models.IntegerField(null=True,
                                              verbose_name="Цена")),
                (
                    "manufacturer",
                    models.CharField(max_length=255,
                                     verbose_name="Производитель"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "db_table": "Products",
                "ordering": ["-price", "name"],
            },
        ),
    ]
