version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  Tech_Case:
    image: docker_test2:latest
    container_name: docker_test2
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data: